import type { Compound } from "./compoundsApi";

export const COMPOUNDS_MOCK: Compound[] = [
    {
        id: 1,
        title: "Метан",
        formula: "CH₄",
        class: "Алканы",
        specificH2oVolume: 44.8,
        specificCo2Volume: 22.4,
        imageUrl: null,
        videoUrl: null,
        description: "Colorless, odorless gas that is lighter than air and insoluble in water",
    },
    {
        id: 2,
        title: "Этилен",
        formula: "C₂H₄",
        class: "Алкены",
        specificH2oVolume: 44.8,
        specificCo2Volume: 44.8,
        imageUrl: null,
        videoUrl: null,
        description: "Colorless gas with a sweetish odor, relatively non-toxic, and poorly soluble in water",
    },
    {
        id: 3,
        title: "Ацетилен",
        formula: "C₃H₈",
        class: "Алкины",
        specificH2oVolume: 22.4,
        specificCo2Volume: 44.8,
        imageUrl: null,
        videoUrl: null,  
        description: "Colorless gas with a faint garlic-like odor, lighter than air, and poorly soluble in water",
    },
    {
        id: 4,
        title: "Бензол",
        formula: "C₆H₆",
        class: "Арены",
        specificH2oVolume: 67.2,
        specificCo2Volume: 134.4,
        imageUrl: null,
        videoUrl: null,
        description: "Colorless, highly flammable liquid with a characteristic aromatic odor, insoluble in water but miscible with organic solvents",
    },
    {
        id: 5,
        title: "Этанол",
        formula: "C₂H₅OH",
        class: "Спирты",
        specificH2oVolume: 67.2,
        specificCo2Volume: 44.8,
        imageUrl: null,
        videoUrl: null,
        description: "Volatile, flammable, colorless liquid with a characteristic alcoholic odor, completely miscible with water",
    },
    {
        id: 7,
        title: "Название",
        formula: "Формула",
        class: "Органические",
        specificH2oVolume: 0,
        specificCo2Volume: 0,
        imageUrl: null,
        videoUrl: null,
        description: "An abstract compound, no certain properties",
    },
];