import type { Compound } from "./compoundsApi";

export const COMPOUNDS_MOCK: Compound[] = [
    {
        id: 1,
        title: "Метан",
        formula: "CH₄",
        class: "Алканы",
        specificH2oVolume: 44.8,
        specificCo2Volume: 22.4,
        imageUrl: "methane.png",
        videoUrl: "methane.mp4",
    },
    {
        id: 2,
        title: "Этанол",
        formula: "C₂H₅OH",
        class: "Спирты",
        specificH2oVolume: 67.2,
        specificCo2Volume: 44.8,
        imageUrl: "ethanol.png",
        videoUrl: "ethanol.mp4",
    },
    {
        id: 3,
        title: "Этилен",
        formula: "C₂H₄",
        class: "Алкены",
        specificH2oVolume: 44.8,
        specificCo2Volume: 44.8,
        imageUrl: "ethylene.png",
        videoUrl: "ethylene.mp4",
    },
    {
        id: 4,
        title: "Бензол",
        formula: "C₆H₆",
        class: "Арены",
        specificH2oVolume: 67.2,
        specificCo2Volume: 134.4,
        imageUrl: "benzol.png",
        videoUrl: "benzol.mp4",
    },
    {
        id: 5,
        title: "Ацетилен",
        formula: "C₃H₈",
        class: "Алкины",
        specificH2oVolume: 22.4,
        specificCo2Volume: 44.8,
        imageUrl: "acetylene.png",
        videoUrl: "acetylene.mp4",
    },
    {
        id: 6,
        title: "Соединение",
        formula: "Формула",
        class: "Класс",
        specificH2oVolume: 111,
        specificCo2Volume: 222,
    },
];